### ISSUE TITLE
Get rid of __pycache__ folders

### ISSUE THREAD

**Issue by SqueakyBeaver** [SqueakyBeaver/BandBot#1]
Why won't they go away? Please help!!!

**Comment by 96RadhikaJadhav** [comment]
@SqueakyBeaver  Did you mean just deleting the _pycache_ folder ?

**Comment by Pranay0302** [comment]
.gitignore file only applies for the untracked files, you need to remove the pycache folders with `git rm` command and then you can get rid of __pycache__ folders

**Comment by Pranay0302** [comment]
@96RadhikaJadhav by deleting the pycache folders once, won't give you the solution because when you run the program or bot in this case, pycache folders will be regenerated.

**Comment by SqueakyBeaver** [comment]
Ah, okay. I was wondering what the heck the issue was. Thanks, all!
